### PR TITLE
Autotools

### PR DESCRIPTION
**Pull request by dblommesteijn**
Using autotools (autoconf, automake and libtool) to compile and link oolib. This enables platform independent usage with Linux and OSX.

### CODE REVIEW

**Comment by dblommesteijn** [comment]
Added a flag to set an alternate `pcre` location: `./configure --with-pcre=/usr/local`

Tested on SLES11sp3:
```bash
autoreconf -vif
./configure LIBS=-lrt --with-pcre=/usr/local
make
```

**Comment by walterdejong** [comment]
Thanks ;)

**Comment by walterdejong** [comment]
Sorry!?
See also #4 
I think you forgot `-I../include` somewhere or so.

**Comment by dblommesteijn** [comment]
Weird I'll try to repair, what's the workflow you're using?

**Pull request merged**
